"""Data models module.

This module defines:
1. SQLAlchemy ORM model (Task) for database representation
2. Pydantic schemas for request/response validation
"""

from sqlalchemy import Column, Integer, String, Boolean, DateTime
from sqlalchemy.orm import declarative_base
from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

from app.db import Base


# ============================================================================
# SQLAlchemy ORM Model
# ============================================================================

class Task(Base):
    """SQLAlchemy Task model for database representation.
    
    Represents a task in the database with the following fields:
    - id: Primary key (auto-generated)
    - title: Task title (required, max 255 characters)
    - description: Task description (optional, max 2000 characters)
    - completed: Task completion status (default: False)
    """
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(255), nullable=False)
    description = Column(String(2000), nullable=True)
    completed = Column(Boolean, default=False, index=True)

    def __repr__(self) -> str:
        return f"<Task(id={self.id}, title='{self.title}', completed={self.completed})>"


# ============================================================================
# Pydantic Schemas for Request/Response Validation
# ============================================================================

class TaskBase(BaseModel):
    """Base schema for task data (shared fields)."""
    title: str = Field(..., min_length=1, max_length=255, description="Task title")
    description: Optional[str] = Field(
        None, max_length=2000, description="Optional task description"
    )
    completed: bool = Field(False, description="Task completion status")


class TaskCreate(TaskBase):
    """Schema for creating a new task.
    
    Used for POST request validation.
    Inherits all fields from TaskBase.
    """
    pass


class TaskUpdate(BaseModel):
    """Schema for updating an existing task.
    
    Used for PUT request validation.
    All fields are optional for partial updates.
    """
    title: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = Field(None, max_length=2000)
    completed: Optional[bool] = None


class TaskResponse(TaskBase):
    """Schema for task response (includes id).
    
    Used for GET responses.
    Includes the task ID which is auto-generated by the database.
    """
    id: int = Field(..., description="Task unique identifier")

    class Config:
        from_attributes = True  # Allow population from ORM models
